/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package comp_la2gpa_zapata.ventanas;

import comp_la2gpa_zapata.procesos.Archivos;
import comp_la2gpa_zapata.procesos.Lexema;
import comp_la2gpa_zapata.procesos.Triplo;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author corin
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        lblArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuAbrir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuSumar = new javax.swing.JMenuItem();
        Triplos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblArchivo.setText("Archivo");

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane2.setViewportView(txtSalida);

        jMenu2.setText("Archivo");

        mnuAbrir.setText("Abrir");
        mnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAbrir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Procesos");

        mnuSumar.setText("Identifica Lexemas");
        mnuSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSumarActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSumar);

        Triplos.setText("Generar Triplos");
        Triplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriplosActionPerformed(evt);
            }
        });
        jMenu3.add(Triplos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void mnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirActionPerformed
        File f = Archivos.getArchivo(this);
        String nomArchivo = f.getAbsolutePath();
        //"C:\\Users\\corin\\Documents\\ITZ\\Lenguajes y Autómatas II\\prueba.txt"
        String contenido = Archivos.getContenido(nomArchivo);
        txtContenido.setText(contenido);
    }//GEN-LAST:event_mnuAbrirActionPerformed


    private void mnuSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSumarActionPerformed

        String datos = txtContenido.getText(); // Obtén el texto de txtContenido
        ArrayList<String> listaElementos = Archivos.separaLexemas(datos); // Separa los elementos

//Llama al método asociaList con la instancia actual de Ventana y la lista de elementos
        Archivos.asociaList(this, listaElementos);
    }//GEN-LAST:event_mnuSumarActionPerformed

    private void TriplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriplosActionPerformed
        // TODO add your handling code here:
        String expresion = txtContenido.getText(); // Suponiendo que tienes un campo de entrada llamado TxtEntrada

        // Separar los lexemas usando el método existente
        ArrayList<String> listaLexemas = Archivos.separaLexemas(expresion);

        // Llamar al método triplos para procesar la expresión y mostrar el resultado en txtSalida
        Archivos.triplos(this, listaLexemas);
    }//GEN-LAST:event_TriplosActionPerformed

    /**
     * @param args the command line arguments
     */
    public JTextArea getTxtContenido() {
        return txtContenido;

    }

    public JTextArea getTxtSalida() {
        return txtSalida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Triplos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenuItem mnuSumar;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables

}
